import 'dart:convert';

import 'rep_movement.dart';

/// How much assisted rep tracking an exercise can support.
///
/// These are capability facts about the exercise, not user preferences and not
/// error states. `unsupported` in particular is permanent and physical: it
/// means no sensor site we have can see the rep, so no amount of calibration
/// or consent will ever change it.
enum RepTrackingTier {
  /// Countable, and confident enough to carry an RPE suggestion once
  /// calibrated.
  supported('supported'),

  /// Countable, but never confidently — short range of motion. The review
  /// surface shows a count and never an RPE.
  countOnly('countOnly'),

  /// Countable only from a phone in a front pocket. The wrist is blind
  /// because the hands are anchored to something that does not move.
  pocketOnly('pocketOnly'),

  /// Not countable at either sensor site. Shows no tracking affordance at all.
  unsupported('unsupported');

  const RepTrackingTier(this.id);

  final String id;

  static RepTrackingTier fromId(String? id) {
    for (final t in RepTrackingTier.values) {
      if (t.id == id) return t;
    }
    // An unknown tier is treated as no capability rather than as the most
    // permissive one. A malformed asset must never switch tracking *on*.
    return RepTrackingTier.unsupported;
  }
}

/// Where the sensor has to be for an exercise to be countable.
enum SensorSite {
  /// The watch. Valid when the hand travels or the forearm rotates.
  wrist('wrist'),

  /// The phone in a front trouser pocket, riding the thigh. Valid when the
  /// hands are anchored and the body travels past them.
  pocket('pocket');

  const SensorSite(this.id);

  final String id;

  static SensorSite? fromId(String? id) {
    if (id == null) return null;
    for (final s in SensorSite.values) {
      if (s.id == id) return s;
    }
    return null;
  }
}

/// A derived signal the detector can count cycles on.
///
/// The three are not interchangeable and their amplitudes are not in the same
/// units — see [RepTrackingProfile.minCycleAmplitudeDeg] and
/// [RepTrackingProfile.minCycleAmplitudeMs2].
enum RepChannel {
  /// Angle of the gravity vector against the set's median orientation, in
  /// degrees. **Does not vanish as cadence slows**, which is the whole reason
  /// it exists: a 3-second curl produces roughly 1.1 m/s² at the wrist but
  /// still rotates the forearm through 60°+.
  tilt('tilt'),

  /// Linear-acceleration magnitude, in m/s². Strong for translation and
  /// ballistic work, and proportional to the square of cadence — so it is the
  /// wrong channel for slow, heavy reps.
  dyn('dyn'),

  /// Gyroscope magnitude, in °/s. Separates rotation from translation and
  /// carries rotation about the gravity axis, which [tilt] cannot see.
  rot('rot');

  const RepChannel(this.id);

  final String id;

  static RepChannel? fromId(String? id) {
    if (id == null) return null;
    for (final c in RepChannel.values) {
      if (c.id == id) return c;
    }
    return null;
  }
}

/// One catalogue row's rep-tracking capability, as generated by
/// `tool/derive_rep_profiles.py` into
/// `assets/data/rep_tracking_profiles.json`.
///
/// The asset is the single source of truth for what an exercise supports.
/// Nothing in the app may widen a profile at runtime: an `unsupported` row
/// carries no thresholds at all, so a caller that ignores [tier] and reaches
/// for [minPeriodMs] gets a null rather than a neighbouring family's numbers.
class RepTrackingProfile {
  const RepTrackingProfile({
    required this.slug,
    required this.tier,
    required this.site,
    required this.family,
    required this.channels,
    required this.minCycleAmplitudeDeg,
    required this.minCycleAmplitudeMs2,
    required this.minPeriodMs,
    required this.maxPeriodMs,
    required this.reason,
  });

  /// `ExerciseCatalog.slug`. Keyed on slug and never on name or id, because
  /// the catalogue importer rewrites display names and matches rows on slug by
  /// design (`lib/data/local/tables.dart`).
  final String slug;

  final RepTrackingTier tier;

  /// Null exactly when [tier] is [RepTrackingTier.unsupported].
  final SensorSite? site;

  /// Null exactly when [tier] is [RepTrackingTier.unsupported].
  final RepMovement? family;

  /// Candidate detection channels, best-first. Empty for an unsupported row.
  final List<RepChannel> channels;

  /// Amplitude floor for [RepChannel.tilt], in degrees. Null when the profile
  /// does not use the tilt channel.
  final double? minCycleAmplitudeDeg;

  /// Amplitude floor for [RepChannel.dyn], in m/s².
  final double? minCycleAmplitudeMs2;

  /// Refractory bounds on one cycle. Null for an unsupported row.
  final int? minPeriodMs;
  final int? maxPeriodMs;

  /// Plain-language justification, carried through from the generator so a
  /// "why can't it count my seated leg curl?" question has an answer in the
  /// data rather than in a commit message.
  final String reason;

  /// True when this exercise can be offered at all.
  bool get isTrackable => tier != RepTrackingTier.unsupported;

  /// True when an RPE suggestion may ever be offered for this exercise, given
  /// enough calibration. Short-range work never qualifies.
  bool get supportsRpe => tier == RepTrackingTier.supported;

  factory RepTrackingProfile.fromJson(Map<String, dynamic> json) {
    final tier = RepTrackingTier.fromId(json['tier'] as String?);
    final family = RepMovement.fromId(json['family'] as String?);
    // A row that claims a tier but names an unknown family is a
    // generator/enum mismatch. Degrade to unsupported rather than tracking
    // with defaults borrowed from nowhere.
    final coherent = tier != RepTrackingTier.unsupported && family != null;

    return RepTrackingProfile(
      slug: json['slug'] as String,
      tier: coherent ? tier : RepTrackingTier.unsupported,
      site: coherent ? SensorSite.fromId(json['site'] as String?) : null,
      family: coherent ? family : null,
      channels: coherent
          ? [
              for (final raw in (json['channels'] as List<dynamic>? ?? const []))
                ?RepChannel.fromId(raw as String?),
            ]
          : const [],
      minCycleAmplitudeDeg:
          coherent ? (json['minCycleAmplitudeDeg'] as num?)?.toDouble() : null,
      minCycleAmplitudeMs2:
          coherent ? (json['minCycleAmplitudeMs2'] as num?)?.toDouble() : null,
      minPeriodMs: coherent ? (json['minPeriodMs'] as num?)?.toInt() : null,
      maxPeriodMs: coherent ? (json['maxPeriodMs'] as num?)?.toInt() : null,
      reason: json['reason'] as String? ?? '',
    );
  }
}

/// The loaded set of capability profiles, keyed by slug.
///
/// Loading is asynchronous (it reads an asset) but every query is
/// synchronous, because the callers are widget builds and a pure detection
/// path. Before [load] completes — and if the asset is missing or malformed —
/// the registry is **empty**, and an empty registry reports every exercise as
/// unsupported. That is the correct failure direction: the feature stays
/// invisible rather than appearing with guessed thresholds.
class RepProfileRegistry {
  RepProfileRegistry._(this._bySlug);

  final Map<String, RepTrackingProfile> _bySlug;

  /// The process-wide registry. Replaced exactly once, by [loadFromJson].
  static RepProfileRegistry get instance => _instance;
  static RepProfileRegistry _instance = RepProfileRegistry._(const {});

  /// True once a non-empty registry has been installed.
  static bool get isLoaded => _instance._bySlug.isNotEmpty;

  /// Parses the profiles asset body and installs it as [instance].
  ///
  /// Pure with respect to Flutter — it takes the decoded string rather than
  /// reaching for `rootBundle` — so the whole registry is testable without a
  /// widget binding.
  static RepProfileRegistry loadFromJson(String body) {
    final decoded = jsonDecode(body);
    if (decoded is! List) {
      throw const FormatException('rep_tracking_profiles.json must be a list');
    }
    final bySlug = <String, RepTrackingProfile>{};
    for (final raw in decoded) {
      if (raw is! Map<String, dynamic>) continue;
      final profile = RepTrackingProfile.fromJson(raw);
      bySlug[profile.slug] = profile;
    }
    return _instance = RepProfileRegistry._(Map.unmodifiable(bySlug));
  }

  /// Restores the empty registry. Test-only — production installs a registry
  /// once at startup and never clears it.
  static void resetForTest() => _instance = RepProfileRegistry._(const {});

  /// The profile for [slug], or null when the slug is unknown — a custom
  /// exercise, a pre-v17 catalogue row, or a catalogue newer than the asset.
  RepTrackingProfile? operator [](String? slug) =>
      slug == null ? null : _bySlug[slug];

  int get length => _bySlug.length;

  Iterable<RepTrackingProfile> get all => _bySlug.values;
}
