import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:herculex/features/workouts/presentation/widgets/exercise_artwork_manifest.dart';

/// The artwork manifest is generated by tool/import_exercise_artwork.py. These
/// guard the two ways it can silently rot: a slug listed without a shipped file
/// (a broken image at runtime) and a shipped file no exercise can reach.
void main() {
  final assetDir = Directory('assets/images/exercises');

  test('every manifest slug ships a webp asset', () {
    final missing = [
      for (final slug in kExerciseArtworkSlugs)
        if (!File('${assetDir.path}/$slug.webp').existsSync()) slug,
    ];
    expect(missing, isEmpty, reason: 'run tool/import_exercise_artwork.py');
  });

  test('every shipped asset is listed in the manifest', () {
    final orphans = [
      for (final entity in assetDir.listSync())
        if (entity is File && entity.path.endsWith('.webp'))
          entity.uri.pathSegments.last.replaceAll('.webp', ''),
    ]..removeWhere(kExerciseArtworkSlugs.contains);
    expect(orphans, isEmpty, reason: 'run tool/import_exercise_artwork.py');
  });

  test('every manifest slug is a real catalog exercise', () {
    final catalog =
        jsonDecode(File('assets/data/exercises.json').readAsStringSync())
            as List<dynamic>;
    final slugs = {
      for (final e in catalog) (e as Map<String, dynamic>)['slug'] as String,
    };
    expect(kExerciseArtworkSlugs.difference(slugs), isEmpty);
  });
}
