/// The single source of truth for `ScheduledWorkouts.status`.
///
/// The column is unvalidated free text, so every filter in the app must agree
/// on this set. Read it through [ScheduleStatus] rather than repeating string
/// literals.
library;

abstract final class ScheduleStatus {
  /// Generated by the scheduler and untouched by the user. The only status
  /// re-materializing a program is allowed to delete.
  static const planned = 'planned';

  /// The user has started the session; `completedSessionId` points at it.
  static const inProgress = 'in_progress';

  /// The session was finished.
  static const done = 'done';

  /// The user dragged it to a different date.
  static const moved = 'moved';

  /// Deliberately not trained — skipped by the user or covered by an
  /// `ExternalEvents` vacation/rest range.
  static const skipped = 'skipped';

  static const all = <String>[planned, inProgress, done, moved, skipped];

  /// Statuses that represent user intent and therefore survive re-materialize.
  static const preserved = <String>[inProgress, done, moved, skipped];

  static bool isOpen(String status) =>
      status == planned || status == moved || status == inProgress;

  static String label(String status) => switch (status) {
    planned => 'Planned',
    inProgress => 'In progress',
    done => 'Completed',
    moved => 'Moved',
    skipped => 'Skipped',
    _ => status,
  };
}
