"""Imports the authored exercise illustrations into the Flutter asset bundle.

The source folder holds one square ~1254px PNG per catalog slug (~1.4 MB each,
half a gigabyte in total). Shipping those verbatim is not an option, so every
image is downscaled to a size that still covers the largest on-screen use (the
190pt hero on the exercise details screen at 3x DPR) and re-encoded as WebP.

Run from the repo root:

    python tool/import_exercise_artwork.py [--source DIR] [--check]

`--check` reports coverage without writing anything.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = Path.home() / "OneDrive" / "Desktop" / "Slike vaj"
DEST_DIR = REPO_ROOT / "assets" / "images" / "exercises"
CATALOG = REPO_ROOT / "assets" / "data" / "exercises.json"
MANIFEST = (
    REPO_ROOT
    / "lib"
    / "features"
    / "workouts"
    / "presentation"
    / "exercise_artwork_manifest.dart"
)

# 190pt hero at 3x DPR needs 570px; 640 leaves headroom without bloating the
# bundle. Quality 85 keeps the cyan muscle overlays free of visible banding.
TARGET_PX = 640
WEBP_QUALITY = 85
SOURCE_SUFFIXES = (".png", ".jpg", ".jpeg", ".webp")


def catalog_slugs() -> list[str]:
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    return [e["slug"] for e in data]


def source_images(source: Path) -> dict[str, Path]:
    found: dict[str, Path] = {}
    for path in sorted(source.iterdir()):
        if path.is_dir() or path.suffix.lower() not in SOURCE_SUFFIXES:
            continue
        found[path.stem.lower()] = path
    return found


def convert(src: Path, dest: Path) -> int:
    with Image.open(src) as im:
        im = im.convert("RGB")
        if im.width != im.height:
            side = min(im.width, im.height)
            left = (im.width - side) // 2
            top = (im.height - side) // 2
            im = im.crop((left, top, left + side, top + side))
        if im.width > TARGET_PX:
            im = im.resize((TARGET_PX, TARGET_PX), Image.LANCZOS)
        dest.parent.mkdir(parents=True, exist_ok=True)
        im.save(dest, "WEBP", quality=WEBP_QUALITY, method=6)
    return dest.stat().st_size


def write_manifest(slugs: list[str]) -> None:
    lines = [
        "// GENERATED by tool/import_exercise_artwork.py — do not edit by hand.",
        "//",
        "// Slugs whose illustration ships in assets/images/exercises/. Kept as a",
        "// const set so artwork lookup stays synchronous and cannot resolve to a",
        "// missing asset.",
        "",
        "const Set<String> kExerciseArtworkSlugs = <String>{",
    ]
    lines += [f"  '{slug}'," for slug in sorted(slugs)]
    lines += ["};", ""]
    MANIFEST.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not args.source.is_dir():
        print(f"Source folder not found: {args.source}", file=sys.stderr)
        return 1

    slugs = catalog_slugs()
    images = source_images(args.source)

    matched = [s for s in slugs if s in images]
    missing = [s for s in slugs if s not in images]
    orphans = sorted(set(images) - set(slugs))

    print(f"catalog: {len(slugs)}  artwork: {len(matched)}  missing: {len(missing)}")
    if orphans:
        print(f"source images with no catalog slug ({len(orphans)}): {', '.join(orphans)}")

    if args.check:
        for slug in missing:
            print(f"  missing: {slug}")
        return 0

    total = 0
    for slug in matched:
        total += convert(images[slug], DEST_DIR / f"{slug}.webp")

    # Drop stale assets so a slug removed from the catalog stops shipping.
    keep = {f"{slug}.webp" for slug in matched}
    for path in DEST_DIR.glob("*.webp"):
        if path.name not in keep:
            path.unlink()

    write_manifest(matched)
    print(f"wrote {len(matched)} webp files, {total / 1024 / 1024:.1f} MB total")
    print(f"manifest: {MANIFEST.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
